name: clivar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - ghp-import
  - xarray
  - rioxarray
  - cftime
  - netcdf4
  - h5netcdf
  - intake
  - intake-esm
  - gcsfs
  - cartopy
  - holoviews
  - hvplot
  - geoviews
  - cartopy
  - geopandas
  - pooch
  - dask
  - fsspec
  - s3fs
  - ipycytoscape
  - datashader
  - kerchunk=0.0.7
  - nc-time-axis
  - pip
  - pip:
    - wget
    - sphinx-exercise
    - jupytext
    - nbgitpuller
